### PR TITLE
Merge Janitha's fork with added functionality

### PR DESCRIPTION
**Pull request by jhanrahan-sigsci**
Janitha at splunk as forked our go api to include some additional functionality needed for a terraform provider.  We are also making a terraform provider so we will end up needing most of this added functionality.  Instead of rewriting everything from scratch, we were looking to clean up his repo and merge it.  I have tested all of the endpoints with basic input and it all seems to work.  Matt G gave me some pointers, and hopefully I addressed all of those too.

### CODE REVIEW

**Comment by blhagadorn** [comment]
Hello, our team is also interested in adding this sort of functionality because we are hoping to codify our WAF Site Rules into a sort of IaC.  I'm curious @jhanrahan-sigsci @mattg-sigsci @mattg-sigsci what the SIgnal Sciences roadmap is for a Terraform provider? We would be happy to contribute to such an effort.

**Comment by jhanrahan-sigsci** [comment]
We should be releasing the terraform-provider Monday next week for private beta testing, and it will have support for Site Rules.  If you would like to be part of the beta @alfred-sigsci would be a good person to contact, or I can connect you two.  We'd appreciate it!

**Comment by blhagadorn** [comment]
@jhanrahan-sigsci That would be great! We'd love to test it. Would you mind putting me in contact? Best email to reach would be `bryant@replicated.com`

**Comment by jhanrahan-sigsci** [comment]
reviewed/approved with @marc-sigsci

**Pull request merged**
